### ISSUE TITLE
race on golang-lru 

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#954] opened 2023-05-26 09:04 UTC
```
2023-05-26T11:02:47.599+02:00 INF offchaindatahandler/offchaindatahandler.go:80 > importing data type="election metadata" uri=ipfs://bafybeigv4mfmn3tyusbwmskfn6xhoyvv2i2svdq7pns6dphdivefr62k3q
2023-05-26T11:02:47.599+02:00 INF offchaindatahandler/offchaindatahandler.go:80 > importing data type="election metadata" uri=ipfs://bafybeigv4mfmn3tyusbwmskfn6xhoyvv2i2svdq7pns6dphdivefr62k3q
2023-05-26T11:02:47.599+02:00 INF vochain/app.go:393 > commit block height=1437 txs=1
2023-05-26T11:02:47.599+02:00 INF offchaindatahandler/metadata.go:17 > metadata downloaded successfully from ipfs://bafybeigv4mfmn3tyusbwmskfn6xhoyvv2i2svdq7pns6dphdivefr62k3q (163 bytes)
2023-05-26T11:02:47.599+02:00 INF offchaindatahandler/metadata.go:17 > metadata downloaded successfully from ipfs://bafybeigv4mfmn3tyusbwmskfn6xhoyvv2i2svdq7pns6dphdivefr62k3q (163 bytes)
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 2223 [running]:
github.com/hashicorp/golang-lru/v2/simplelru.(*LRU[...]).Add(0x3e47160, {0xc00e1630e0, 0x41}, {0xc004578a00, 0x9e, 0x200})
	/home/vocdoni/go/pkg/mod/github.com/hashicorp/golang-lru/v2@v2.0.2/simplelru/lru.go:58 +0x1ff
go.vocdoni.io/dvote/data/ipfs.(*Handler).Retrieve(0xc000994d20, {0x3e126d8, 0xc0007b6000}, {0xc00503b720?, 0x2?}, 0x6400000)
	/home/vocdoni/vocdoni-node/data/ipfs/ipfs.go:319 +0x434
go.vocdoni.io/dvote/data/downloader.(*Downloader).handleImport(0xc003e93b60, 0xc00b4d5220)
	/home/vocdoni/vocdoni-node/data/downloader/downloader.go:125 +0x17f
go.vocdoni.io/dvote/data/downloader.(*Downloader).importQueueDaemon(0xc003e93b60, {0x3e12668, 0xc0008d5a40})
	/home/vocdoni/vocdoni-node/data/downloader/downloader.go:158 +0x52
created by go.vocdoni.io/dvote/data/downloader.(*Downloader).Start
	/home/vocdoni/vocdoni-node/data/downloader/downloader.go:71 +0x6d

goroutine 1 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/local/go/src/runtime/time.go:195 +0x135
go.vocdoni.io/dvote/service.(*VocdoniService).Start(0xc008d5dea8)
	/home/vocdoni/vocdoni-node/service/vochain.go:137 +0x394
main.main()
	/home/vocdoni/vocdoni-node/cmd/node/main.go:474 +0xeec

goroutine 6 [select]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc000340420)
	/home/vocdoni/go/pkg/mod/github.com/ipfs/go-log@v1.0.5/writer/writer.go:71 +0x11f
created by github.com/ipfs/go-log/writer.NewMirrorWriter
	/home/vocdoni/go/pkg/mod/github.com/ipfs/go-log@v1.0.5/writer/writer.go:36 +0xca

goroutine 7 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000ffc00)
	/home/vocdoni/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0xad
created by go.opencensus.io/stats/view.init.0
	/home/vocdoni/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x96

goroutine 28 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x0?)
	/home/vocdoni/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
	/home/vocdoni/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:410 +0x
```

**Comment by mvdan** [comment] 2023-05-26 20:41
duplicate of https://github.com/vocdoni/vocdoni-node/issues/940.

**Closed as not planned by mvdan** 2023-05-26 20:41 UTC
