### ISSUE TITLE
module dependency cycle with arbo prevents downgrading bazil.org/fuse

### ISSUE THREAD

**Issue by maektwain** [vocdoni/vocdoni-node#399] opened 2021-12-13 12:11 UTC
**Describe the bug**
Running on mac specifically build leads to fuse error of undefined values

**To Reproduce (please complete the following information)**

run on mac os X  

`` go build ./cmd/dvotecli   ``

**Current behavior**
```
# bazil.org/fuse
../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/error_std.go:26:20: undefined: errNoXattr
../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:171:12: undefined: mount
../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:236:24: undefined: maxWrite
../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:425:32: undefined: maxWrite
../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:810:12: undefined: openFlags
../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:828:18: undefined: openFlags
../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:845:18: undefined: openFlags
../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:868:18: undefined: openFlags
../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:991:12: undefined: openFlags
../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:1413:20: undefined: maxWrite
../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:1413:20: too many errors

```
**Expected behavior**
It should build 

**System (please complete the following information):**

- OS: Mac OS X 11.5.2
- Software version
- Commit hash 

**Additional context**

**Comment by mvdan** [comment] 2021-12-15 14:00
Unfortunately, this is a bug caused by upstreams - ipfs and fuse. See https://github.com/ipfs/go-ipfs/issues/7889.

I'll see if we can downgrade bazil, in the meantime. That's the same temporary workaround go-ipfs ships with.

**Comment by jordipainan** [comment] 2022-01-26 10:48
Any updates on this? Otherwise we can close the issue :)

**Comment by mvdan** [comment] 2022-01-26 17:28
This is blocked at the moment, because dvote depends on arbo, and arbo depends on dvote; and that dependency cycle with MVS means we can't downgrade the fuse dependency (without a replace directive, anyway).

With @p4u and @arnaucube we discussed this and I think we agreed on merging the arbo module+repository into this one, so I've retitled the issue. Please correct me if I misremember.

In the meantime, I will post a PR with a _temporary fix_ in the form of a replace directive.

**Closed as completed** 2023-02-01 09:07 UTC
Labels: bug
