### ISSUE TITLE
CI: Cannot get merkle proof

### ISSUE THREAD

**Issue by vdo** [vocdoni/vocdoni-node#129] opened 2021-03-16 09:11 UTC
A possible race condition causes the vochaintest to fail sometimes during the `compose-test` job:
```
2021-03-15T11:29:11Z    INFO    vochaintest/vochaintest.go:137    census created and published
Root: dd9268afeaf99fb790cef9f5279d41c05aea3323afa6504c1a1885cf2ac0b884
URI: ipfs://Qmc4vo1nGiKmraAqdafGSHMRbphwrAdbc7XV1DWnuZxfG3
2021-03-15T11:29:11Z    INFO    client/api.go:193    generating proofs...
2021-03-15T11:29:11Z    INFO    client/api.go:629    get root
2021-03-15T11:29:11Z    FATAL    vochaintest/vochaintest.go:140    cannot get merkle proof: ()
main.censusGenerate
    /src/cmd/vochaintest/vochaintest.go:140
main.mkTreeVoteTest
    /src/cmd/vochaintest/vochaintest.go:220
main.main
    /src/cmd/vochaintest/vochaintest.go:88
runtime.main
    /usr/local/go/src/runtime/proc.go:204
2021-03-15T11:29:11Z    INFO    vochaintest/vochaintest.go:137    census created and published
Root: c79afe3bf9483676cbdffdc7ad501cb43bbc8c0bb8b423b5c00c691d2a65d2cf
```

**Comment by vdo** [comment] 2021-03-16 09:15
https://github.com/vocdoni/vocdoni-node/runs/2112106737

**Comment by mvdan** [comment] 2021-03-29 15:42
@vdo is there a way to also see the logs for the server the client was talking to? It returned an empty proof, and there isn't an error message either, so I have nothing to start an investigation with.

I also looked at the underlying implementation of genProof, and as far as I can tell it's not designed to return an empty proof unless something goes wrong. Plus, gravitontree never marshals a proof into zero bytes either.

So I think there's an error of some sort on the server side, and I've run the tests locally a bunch of times but I can't get it to fail like it did on CI. If this error is rare, I'd personally add printing of server logs if vochaintest fails, and next time we get a failure we can investigate better.

**Comment by vdo** [comment] 2021-04-01 09:11
Sorry for the late response.

For some reason, the post run logs output was removed from the test script, maybe to avoid too much logging in gitlab, here:
https://github.com/vocdoni/vocdoni-node/blob/master/dockerfiles/testsuite/start_test.sh#L46

I suggests enabling them back, if the bug happens again.

**Comment by mvdan** [comment] 2021-04-01 09:23
> I suggests enabling them back, if the bug happens again.

Sounds good. I'd even consider enabling them now, because I'm pretty sure that GitHub Actions deals with long output pretty well. It has a way to download the raw output, anyway.

If we find that the UI gets too slow when we print the entire output, we could also just print the logs when the tests failed.

**Comment by vdo** [comment] 2021-04-01 09:37
https://github.com/vocdoni/vocdoni-node/pull/146

**Comment by vdo** [comment] 2021-08-17 08:57
@mvdan  Can we close this issue?

**Comment by mvdan** [comment] 2021-08-17 09:19
Sounds good. Any bug that can't be reproduced and hasn't been seen for six months is as good as dead.

**Comment by altergui** [comment] 2022-09-28 08:45
got this one today, it looks that this race is still there, just happens very seldom and (i'd guess) when CI server is under load

https://github.com/vocdoni/vocdoni-node/actions/runs/3141870432/jobs/5104802900#step:3:10878
```
2022-09-28T08:27:50Z	FATAL	vochaintest/vochaintest.go:923	[http://gateway0:9090/dvote] cannot get merkle proof: (key not found)
main.mkTreeAnonVoteTest.func2
	go.vocdoni.io/dvote/cmd/vochaintest/vochaintest.go:923
```
[logs_4266.zip](https://github.com/vocdoni/vocdoni-node/files/9663135/logs_4266.zip)

reopening just in case there's something interesting behind it.

**Comment by altergui** [comment] 2024-03-06 15:23
never happened again, closing

**Closed as completed by altergui** 2024-03-06 15:23 UTC
Labels: bug
