### ISSUE TITLE
Proto name conflict

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#162] opened 2021-04-29 10:05 UTC
We are still having this warning.
```
2021/04/29 12:04:37 WARNING: proto: file "vochain/vochain.proto" has a name conflict over dvote.types.v1.UNKNOWN
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```

**Comment by mvdan** [comment] 2021-04-29 10:48
We used to have a similar warning, caused by badger v2. My fix made it into v3, so that warning is gone.

This is a new warning. It's a namespace conflict in our protobuf definitions:

https://github.com/vocdoni/dvote-protobuf/blob/33cf17b307f04536407aeda8a3d26b08ec91360e/src/ipfsSync/ipfssync.proto#L8

https://github.com/vocdoni/dvote-protobuf/blob/33cf17b307f04536407aeda8a3d26b08ec91360e/src/vochain/vochain.proto#L35

Those enum names in protobuf are scoped to the entire package, and both `src/ipfsSync` and `src/vochain` are the same protobuf package, `dvote.types.v1`.

Assuming we want to keep them under the same protobuf package, all enum names need to be made conflict-free. What I would personally do is move the enum types outside of the package scope, moving them inside each of the message types:

```
message IpfsSync {
    enum Type {
        UNKNOWN = 0;
        HELLO = 1;
        UPDATE = 2;
        FETCH = 3;
        FETCHREPLY = 4;
    }
    Type msgtype = 1;
    string address = 2;
    string multiaddress = 3;
    bytes hash = 4;
    repeated IpfsPin pinList = 5;
    uint32 timestamp = 6;
}
```

And the same for the other enum. This doesn't add redundancy, because the old `IpfsSyncType` name is now `IpfsSync.Type`. And all the enum names are now scoped just within `IpfsSync`.

If we really need global enum names, we could always do that, but then you have to be extra careful with collisions. And I don't think global enums are necessary, in general.

**Comment by mvdan** [comment] 2021-04-29 10:49
Also, the change above should be backwards-compatible, I'm pretty sure. The underyling types are not changing, and the encoding shouldn't change either.

**Comment by p4u** [comment] 2021-04-29 10:59
> Assuming we want to keep them under the same protobuf package

I think we don't need to have all of them under the same package. It was build this way for simplicity, but its not a requirement.

**Comment by mvdan** [comment] 2021-04-29 11:08
That's also an option. Though splitting the protobuf repo into many protobuf packages seems like a larger refactor that would require changes in all users of the generated code, whereas moving the enums would only require small tweaks in the code using those two enums.

Also, even if they were separate packages, I still think I'd avoid global enums :)

**Comment by p4u** [comment] 2021-05-04 13:20
Ok to the enums change. Lets see if this is actually backwards compatible. If not we can handle it but will require some coordination between the different libraries using the protobuf types.

**Comment by mvdan** [comment] 2021-05-17 12:54
Fixed the root cause in https://github.com/vocdoni/dvote-protobuf/pull/14, and https://github.com/vocdoni/vocdoni-node/pull/175 is pulling it into vocdoni-node. Closing as that should be an easy merge.

**Closed as completed by mvdan** 2021-05-17 12:54 UTC
