### ISSUE TITLE
CI: account not found

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#904] opened 2023-05-04 11:40 UTC
Occasionally, the CI fails as follows. 

```
2023-05-04 11:37:23+00:00 ### Logs from failed test (e2etest_cenususizelection) ###
2023-05-04T11:35:36.893Z INF end2endtest/main.go:113 > logger construction succeeded at level debug with output stdout
2023-05-04T11:35:36.893Z INF end2endtest/main.go:114 > starting end2endtest version=0e29576-dirty
2023-05-04T11:35:36.893Z INF end2endtest/main.go:118 > no keys passed, generated random private key: [675b5d6eed9dc11cf3a7e05951fb3f9738ffa198a14f27da0b11191d2f853916]
2023-05-04T11:35:36.893Z INF end2endtest/main.go:128 > privkey 675b5d6eed9dc11cf3a7e05951fb3f9738ffa198a14f27da0b11191d2f853916 = account 0x976c4215842f3b5Df91cb707f5eb92fF1A3Ee3e5
2023-05-04T11:35:36.893Z DBG end2endtest/main.go:173 > connecting to http://gateway0:9090/v2
2023-05-04T11:35:36.893Z DBG apiclient/client.go:166 > http request body=null path=/v2/chain/info type=GET
2023-05-04T11:35:36.895Z DBG apiclient/client.go:166 > http request body=null path=/v2/accounts/0x976c4215842f3b5Df91cb707f5eb92fF1A3Ee3e5 type=GET
2023-05-04T11:35:36.897Z INF end2endtest/helpers.go:65 > creating Vocdoni account 0x976c4215842f3b5Df91cb707f5eb92fF1A3Ee3e5
2023-05-04T11:35:36.897Z DBG data/ipfs.go:354 > computed cid: bagaaieraeryh2ucpq7amm42fpv6uaevlsri4hsb7io36e5hqwgreyoq3qw4a
2023-05-04T11:35:36.897Z DBG apiclient/client.go:166 > http request body={"metadata":"eyJ2ZXJzaW9uIjoiMS4wIiwibmFtZSI6eyJkZWZhdWx0IjoidGVzdCBhY2NvdW50IDB4OTc2YzQyMTU4NDJmM2I1RGY5MWNiNzA3ZjVlYjkyZkYxQTNFZTNlNSJ9LCJkZXNjcmlwdGlvbiI6eyJkZWZhdWx0IjoidGVzdCBkZXNjcmlwdGlvbiJ9fQ==","metadataURL":"","txHash":"","txPayload":"CsgBSsUBCBcQABpEaXBmczovL2JhZ2FhaWVyYWVyeWgydWNwcTdhbW00MmZwdjZ1YWV2bHNyaTRoc2I3aW8zNmU1aHF3Z3JleW9xM3F3NGEiFJdsQhWELztd+Ry3B/Xrkv8aPuPlKmMKHgjexZ75AhIUl2xCFYQvO135HLcH9euS/xo+4+UYZBJBExVR4NrIBKjdOKPFewb5LBPnvwdkPImZzTCgEsGxBSQUWMR9kWitXEeH1PArioO0gEuWhvMQH5gID2f74dGO2AASQRG9QVkG2vdw/TuySCaGnqFh9a8fB7JQpv7wz6bMl6ooF975WAPWgsmD0WASbzSP1KLft05cOk2MogQX+EXizbkB"} path=/v2/accounts type=POST
2023-05-04T11:35:36.927Z DBG apiclient/client.go:166 > http request body=null path=/v2/chain/transactions/reference/e70df42876746cf226a2f2b9c27d074919545db4cb3419190a158a4c20e9b1b1 type=GET
2023-05-04T11:35:37.928Z DBG apiclient/client.go:166 > http request body=null path=/v2/chain/transactions/reference/e70df42876746cf226a2f2b9c27d074919545db4cb3419190a158a4c20e9b1b1 type=GET
2023-05-04T11:35:38.929Z DBG apiclient/client.go:166 > http request body=null path=/v2/chain/transactions/reference/e70df42876746cf226a2f2b9c27d074919545db4cb3419190a158a4c20e9b1b1 type=GET
2023-05-04T11:35:39.929Z DBG apiclient/client.go:166 > http request body=null path=/v2/chain/transactions/reference/e70df42876746cf226a2f2b9c27d074919545db4cb3419190a158a4c20e9b1b1 type=GET
2023-05-04T11:35:40.93Z DBG apiclient/client.go:166 > http request body=null path=/v2/chain/transactions/reference/e70df42876746cf226a2f2b9c27d074919545db4cb3419190a158a4c20e9b1b1 type=GET
2023-05-04T11:35:41.931Z DBG apiclient/client.go:166 > http request body=null path=/v2/chain/transactions/reference/e70df42876746cf226a2f2b9c27d074919545db4cb3419190a158a4c20e9b1b1 type=GET
2023-05-04T11:35:42.933Z DBG apiclient/client.go:166 > http request body=null path=/v2/chain/transactions/reference/e70df42876746cf226a2f2b9c27d074919545db4cb3419190a158a4c20e9b1b1 type=GET
2023-05-04T11:35:43.933Z DBG apiclient/client.go:166 > http request body=null path=/v2/chain/transactions/reference/e70df42876746cf226a2f2b9c27d074919545db4cb3419190a158a4c20e9b1b1 type=GET
2023-05-04T11:35:44.934Z DBG apiclient/client.go:166 > http request body=null path=/v2/chain/transactions/reference/e70df42876746cf226a2f2b9c27d074919545db4cb3419190a158a4c20e9b1b1 type=GET
2023-05-04T11:35:45.936Z DBG apiclient/client.go:166 > http request body=null path=/v2/chain/transactions/reference/e70df42876746cf226a2f2b9c27d074919545db4cb3419190a158a4c20e9b1b1 type=GET
2023-05-04T11:35:46.937Z DBG apiclient/client.go:166 > http request body=null path=/v2/chain/transactions/reference/e70df42876746cf226a2f2b9c27d074919545db4cb3419190a158a4c20e9b1b1 type=GET
2023-05-04T11:35:47.077Z DBG apiclient/client.go:166 > http request body=null path=/v2/accounts/0x976c4215842f3b5Df91cb707f5eb92fF1A3Ee3e5 type=GET
2023-05-04T11:35:47.078Z FTL end2endtest/main.go:145 > API error: 404 ({"error":"account not found: 0x976c4215842f3b5Df91cb707f5eb92fF1A3Ee3e5","code":4003}
)
```

**Comment by altergui** [comment] 2023-05-31 10:34
i'm pretty confident this was caused by the buggy mempool prune code introduced in https://github.com/vocdoni/vocdoni-node/commit/8168c864a8a30c9cb1bbf3c3e80e290dcc86c3df
fixed in #966 

i don't have the logs to confirm, like i did in #947 but i'll close this issue anyway, if it DOES happen again, reopen

**Closed as completed by altergui** 2023-05-31 10:34 UTC
Labels: bug, ci
